### ISSUE TITLE
Update go GNOME 3.32

### ISSUE THREAD

**Issue by fgrabenstaetter** [thilomaurer/pwcalc#11]
Unfortunately, this nice extension don't longer work with the new GNOME 3.32 release :(

**Comment by thilo-maurer** [comment]
Checked this with Ubuntu 19.04 and getting the error
```
gnome-shell[13215]: Extension "pwcalc@thilomaurer.de" had error: TypeError: Object 0x7f296504bba0 is not a subclass of GObject_Object, it's a Object
```

**Comment by thilomaurer** [comment]
@fgrabenstaetter Please verify

**Comment by fgrabenstaetter** [comment]
> @fgrabenstaetter Please verify

Thanks, it work
