### ISSUE TITLE
Upgrade to Gnome Shell 3.14.1

### ISSUE THREAD

**Issue by FelixVanderJeugt** [thilomaurer/pwcalc#3]
Gnome shell 3.14 had been around for some time, it'd be nice if this extension was made compatible. [This guy](http://michaeltunnell.com/blog/16-linux/52-my-updated-314-packages-for-gnome-extensions) upgraded some other extensions, they might be useful examples.

**Comment by thilomaurer** [comment]
Now available for 3.14
