### ISSUE TITLE
Compatibility to gnome 3.18

### ISSUE THREAD

**Issue by nielsmde** [thilomaurer/pwcalc#4]
I just tried to install the extension for gnome 3.18, by adding this version to `metadata.json`.
As far as I can tell, all seems to work fine. It would be great if you could push that to the repo, so the extension could be installed via extensions.gnome.org.

Niels

**Comment by thilomaurer** [comment]
Done so. Along with some other improvements.

Expect it to be available for easy-install in a few days at https://extensions.gnome.org/extension/825/password-calculator/
