### ISSUE TITLE
Where are the password aliases stored

### ISSUE THREAD

**Issue by GizmoCodes** [thilomaurer/pwcalc#5]
So I screwed up my distro, and it doesn't really have a repair function, so I want to reinstall. Problem is, a lot of my passwords are calculated using this; that normally wouldn't be a problem, if I wasn't so forgetful and remembered my aliases I set for my passwords.

So where are the password aliases stored, or are they even stored in a file?

**Comment by thilo-maurer** [comment]
Settings are stored in conf at the path /org/gnome/shell/extensions/pwcalc.

So if you are still able to get a console entering the command will show you all your recent aliases:
`dconf read /org/gnome/shell/extensions/pwcalc/recenturls`

If not copy the file ~/.config/dconf/user to a new system and/or run
`cat ~/.config/dconf/user | grep --text "recenturls.*"`

**Comment by GizmoCodes** [comment]
Ahh, thanks!

**Comment by thilomaurer** [comment]
Most recent version added script `list-extension-data` to list all of this extension's stored data.
Full path should be `~/.local/share/gnome-shell/extensions/pwcalc@thilomaurer.de/list-extension-data`
