### ISSUE TITLE
Wayland compatibility

### ISSUE THREAD

**Issue by nielsmde** [thilomaurer/pwcalc#8]
I tried using the pwcalc extension under Fedora 23 & Wayland, the future replacement of the X11 window manager.
The extension shows up, but copy to clipboard does not work. More specifically, it seems as it just overrides the clipboard with an empty string.

Would be great if this could be fixed in the future, since Wayland should be feature complete with the release of Fedora 24 in June.

Cheers Niels

**Comment by thilomaurer** [comment]
True, checked issue for Fedora23 using GNOME-Wayland.
However no issues using Fedora24-Alpha.
Therefore assuming issue with wayland on fedora23, no issue with pwcalc.
Agree?

**Comment by nielsmde** [comment]
I think F24 ships Gnome 3.20 which has some changes regarding Copy and paste.
So this is an Issue with Gnome 3.18 + Wayland, which is not production ready anyway. 
So I agree this Issue may be closed.

**Comment by nielsmde** [comment]
I recently installed Fedora 24 and am using Wayland right now. Sadly pwcalc does not copy anything to clipboard. are you sure you used Wayland with the F24-Alpha?

Seems like this problem is also present in the clipboard-indicator extension, which uses the same clipboard mechanism, as far as I can see. 

Tudmotu/gnome-shell-extension-clipboard-indicator#41

Would be great if we could find a fix. Is there any reference of the Gnome javascript API? If so I would have a look and try to find a solution.

**Comment by thilomaurer** [comment]
I confirm the issue when using Wayland in Fedora 24.

The following code is used in the extension to write to the clipboard:
```js
const St = imports.gi.St;
const CLIPBOARD_TYPE = St.ClipboardType.CLIPBOARD;
const clipboard = St.Clipboard.get_default();
clipboard.set_text(CLIPBOARD_TYPE,"text for the clipboard");
```
This in turn calls `st_clipboard_set_text(...)` at https://git.gnome.org/browse/gnome-shell/tree/src/st/st-clipboard.c#n375
This function calls a bunch of X server functions which should finally deliver the clipboard text to the clipboard buffer, but
* Can the same code be valid when running on Wayland?
* Should the FIXME be resolved?

**Comment by thilomaurer** [comment]
I confirm the issue when using Wayland in Fedora 24 and Fedora 23.
There is however NO issue when using Wayland in Ubuntu 16.04.1 LTS.

**Comment by nielsmde** [comment]
That's strange. Any idea what Ubuntu is doing different?

**Comment by thilomaurer** [comment]
Sorry, I messed up. It is also broken in Ubuntu 16.04.1

**Comment by thilomaurer** [comment]
Patch for Gnome Shell Toolkit is available, see https://bugzilla.gnome.org/show_bug.cgi?id=769619

**Comment by nielsmde** [comment]
Sounds promising, I hope this patch will be accepted soon.

**Comment by nielsmde** [comment]
So just as an update: I recently upgraded to Fedora 25 and your extension works under Wayland!
