### ISSUE TITLE
HMAC_SHA1 algo is wrong

### ISSUE THREAD

**Issue by nE0sIghT** [thilomaurer/pwcalc#9]
Hello.
While reproducing your password algos in browser extension I found, that HMAC_SHA1 algo of your GNOME Shell extension produces unexpected password.

For example, in your extension HMAC SHA1 password of alias=1 and secret=1 produces (16-chars cropped) "mhE8CzTID+E3kDlo".
And real HMAC SHA1 base64-encoded signature of key=1 and data=1 is "WwwVfU52ckRMQQM1YVVIOe0f0tY=".

**Comment by nE0sIghT** [comment]
The problem is at the [line 324 of extension.js](https://github.com/thilomaurer/pwcalc/blob/master/extension.js#L324): for hash calculation you are using outer pad concatenated with hashed (inner pad + data). But hashed (inner pad + data) is hex-encoded string while it should not be hex-encoded.
You should apply same conversion for hashed (inner pad + data) as in the line 326 for final hash.

**Comment by nE0sIghT** [comment]
This also applies to [line 316](https://github.com/thilomaurer/pwcalc/blob/master/extension.js#L316) in case secret is longer than 64 bytes.

**Comment by thilomaurer** [comment]
Yes, you are correct.
Trouble is, if I fix this, users' generated passwords will "change".
Question therefore is: With the current implementation, can the "key" be derived from the wrongly calculated HMAC-SHA1?
The current implementation is ```HMAC-SHA1=hash(o_key_pad ∥ hash_as_hex(i_key_pad ∥ message))```

**Comment by nE0sIghT** [comment]
> Question therefore is: With the current implementation, can the "key" be derived from the wrongly calculated HMAC-SHA1?

I can not say for sure, however hex-encoded SHA-1 hash string is limited to dictionary of 16 symbols (0-9,a-f) which is lower than possible alias dictionary.
However it should be longer than avg domain name or email address.

Anyway it's possible to provide both implementations in next extensions version (right and broken) and inform users through some popup that from August 2017 until current versions there was error in HMAC-SHA-1 implementation and is' better to change calculated passwords IMHO.

**Comment by thilomaurer** [comment]
I deem the method as equally safe (and therefore safe) as the original plain SHA1 method, since the HMAC-SHA1's outer SHA1 is done right.

I nevertheless plan to fix the implementation and move upgrading users to the compatibility mode "HMAC-SHA1-INEXACT".

FYI: The mode HMAC-SHA1 was only a later refinement, such that an attacker gaining knowledge about a single alias and the generated password would be unable to generate further passwords without knowing the single secret. Such passwords would however be of no use to the attacker, as explained in #6.

**Comment by nE0sIghT** [comment]
> I nevertheless plan to fix the implementation and move upgrading users to the compatibility mode "HMAC-SHA1-INEXACT".

Thanks for great extension!
When/if you will upload new version to e.g.o. feel free to ping me and I will approve it ASAP.

**Comment by thilomaurer** [comment]
Prepared fix at branch [fix-hma-sha1](/thilomaurer/pwcalc/commits/fix-hmac-sha1).

Would be great if you could verify/test new implementation.

**Comment by nE0sIghT** [comment]
Looks good to me

**Comment by thilomaurer** [comment]
merged to master; new version submitted to gnome-extensions
